---
epubli-taschenbuch-10pt:
    type: print
    format: taschenbuch-10pt
    print: www.epubli.de
    papersize: taschenbuch
    fontsize: 10pt
    cover: cover-taschenbuch-epubli.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Softcover
    printerName: epubli
  
epubli-taschenbuch-11pt:
    type: print
    format: taschenbuch-10pt
    print: www.epubli.de
    papersize: taschenbuch
    fontsize: 11pt
    cover: cover-taschenbuch-epubli.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Softcover
    printerName: epubli

epubli-taschenbuch-booklet-11pt:
    type: print
    format: taschenbuch-10pt
    print: www.epubli.de
    papersize: taschenbuch
    fontsize: 11pt
    cover: cover-taschenbuch-booklet-epubli.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Booklet
    printerName: epubli

epubli-a5-booklet-10pt:
    type: print
    format: a5-10pt
    print: www.epubli.de
    papersize: a5
    fontsize: 10pt
    cover: cover-a5-booklet-epubli.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Booklet
    printerName: epubli
 
lulu-digest-11pt:
    type: print
    format: digest-11pt
    papersize: digest
    fontsize: 11pt
    print: www.lulu.com
    cover: cover-digest-lulu.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Softcover
    printerName: lulu

lulu-a5-booklet-11pt:
    type: print
    format: booklet-a5-11pt
    papersize: a5
    fontsize: 11pt
    print: www.lulu.com
    cover: cover-digest-lulu.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Booklet
    printerName: lulu

lulu-digest-10pt:
    type: print
    format: digest-10pt
    papersize: digest
    fontsize: 10pt
    print: www.lulu.com
    cover: cover-digest-lulu.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Softcover
    printerName: lulu
 
lulu-a5-10pt:
    type: print
    format: digest-10pt
    papersize: a5
    fontsize: 10pt
    print: www.lulu.com
    cover: cover-a5-lulu.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Softcover
    printerName: lulu
    
    
wirmachendruck-a5-hard-11pt:
    type: print
    format: a5-11pt
    papersize: a5
    fontsize: 11pt
    print: www.wir-machen-druck.de
    cover: cover-a5-hard-wirmachendruck.css
    pandocTemplate: book.latex
    fileType: pdf
    binding: Hardcover
    printerName: wirmachendruck
    
web:
    webCaption: PDF
    type: web
    format: web
    papersize: a5
    fontsize: 10pt
    pandocTemplate: web.latex
    fileType: pdf
epub:
    webCaption: EPub
    type: epub
    format: epub
    pandocTemplate: default.epub
    fileType: epub
