---
-
    name: epubli-taschenbuch-10pt
    type: print
    format: taschenbuch-10pt
    print: www.epubli.de
    papersize: taschenbuch
    fontsize: 10pt
    cover: cover-taschenbuch-epubli.css
    pandocTemplate: book.latex
    fileType: pdf
-
    name: epubli-taschenbuch-11pt
    type: print
    format: taschenbuch-10pt
    print: www.epubli.de
    papersize: taschenbuch
    fontsize: 10pt
    cover: cover-taschenbuch-epubli.css
    pandocTemplate: book.latex
    fileType: pdf
-
    name: lulu-digest-11pt
    type: print
    format: digest-11pt
    papersize: digest
    fontsize: 11pt
    print: www.lulu.com
    cover: cover-digest-lulu.css
    pandocTemplate: book.latex
    fileType: pdf
-
    name: lulu-digest-10pt
    type: print
    format: digest-11pt
    papersize: digest
    fontsize: 11pt
    print: www.lulu.com
    cover: cover-digest-lulu.css
    pandocTemplate: book.latex
    fileType: pdf
-
    name: epub
    type: epub
    format: epub
    pandocTemplate: default.epub
    fileType: epub
