---
-
    name: default
    targets:
        -
            name: lulu-digest
            type: print
            format: digest-11pt
            papersize: digest
            fontsize: 11pt
            print: www.lulu.com
            cover: cover-digest.css
        
        -
            name: lulu-a5
            type: print
            format: a5-11pt
            papersize: a5
            fontsize: 11pt
            print: www.lulu.com
            cover: cover-a5-lulu.css
        
        -
            name: epubli-a5
            type: print
            papersize: a5
            fontsize: 11pt
            format: a5-11pt
            print: www.epubli.de
            cover: cover-a5.css
        
        -
            name: epubli-taschenbuch
            type: print
            format: taschenbuch-11pt
            print: www.epubli.de
            papersize: taschenbuch
            fontsize: 11pt
            cover: cover-taschenbuch.css
        
        -
            name: epub
            type: epub
            format: epub
    
-
    name: default-big
    targets: 
        -
            name: epubli-a5
            type: print
            format: a5-11pt
            papersize: a5
            fontsize: 11pt
            print: www.epubli.de
            cover: cover-a5.css
        -
            name: epub
            type: epub
            format: epub
    
-
    name: digital
    targets:
        -
            name: epub
            type: epub
            format: epub
        
-
    name: small
    targets:
        -
            name: lulu-digest
            type: print
            format: digest-11pt
            papersize: digest
            fontsize: 11pt
            print: www.lulu.com
            cover: cover-digest.css
        
        -
            name: epubli-taschenbuch
            type: print
            format: taschenbuch-11pt
            papersize: taschenbuch
            fontsize: 11pt
            print: www.epubli.de
            cover: cover-taschenbuch.css
        
        -
            name: epub
            type: epub
            format: epub
-
    name: test
    targets:
        -
            name: lulu-digest
            type: print
            format: digest-11pt
            papersize: digest
            fontsize: 11pt
            print: www.lulu.com
            cover: cover-digest.css