---
a4: 
    alias: a4paper
    top: 2cm
    bottom: 2cm
    left: 2.5cm
    right: 2cm
a5: 
    alias: a5paper
    top: 2cm
    bottom: 2cm
    left: 2.5cm
    right: 2cm
taschenbuch: 
    width: 125mm
    height: 190mm
    geometryoptions: ignoreall,twoside
digest: 
    width: 140mm
    height: 216mm
    top: 2cm
    bottom: 2cm
    left: 2.5cm
    right: 2cm